#!/usr/bin/env python3
"""
img2scad_color.py — Generate a color OpenSCAD heightmap from an image.
Each pixel becomes a colored cube, height based on brightness.
"""

from PIL import Image
import numpy as np

# === CONFIG ===
INPUT_IMAGE = "a.png"
OUTPUT_SCAD = "output.scad"
MIN_HEIGHT  = 0.1       # ignore small noise (mm)
PIXEL_SIZE  = 1.0       # mm per pixel (XY)
MAX_HEIGHT  = 10.0      # max Z height (mm)
DOWNSCALE   = 1         # skip every Nth pixel for performance 1=slow >1= faster / lower res

# === LOAD IMAGE ===
img = Image.open(INPUT_IMAGE).convert("RGB")
data = np.asarray(img, dtype=float)[::DOWNSCALE, ::DOWNSCALE, :]

# Convert to grayscale for height
gray = np.dot(data[..., :3], [0.299, 0.587, 0.114])
heights = gray * (MAX_HEIGHT / 255.0)

rows, cols, _ = data.shape

# === WRITE SCAD ===
with open(OUTPUT_SCAD, "w") as f:
    f.write("// Generated by img2scad.py\n")
    for y in range(rows):
        for x in range(cols):
            h = heights[y, x]
            if h < MIN_HEIGHT:
                continue

            r, g, b = (data[y, x] / 255.0)
            f.write(f"color([{r:.3f}, {g:.3f}, {b:.3f}])\n")
            f.write(f"translate([{x * PIXEL_SIZE}, {y * PIXEL_SIZE}, 0])\n")
            f.write(f"cube([{PIXEL_SIZE}, {PIXEL_SIZE}, {h:.2f}]);\n")



'''
Notes:
openSCAD will take forever to load a prebuilt complex openscad file IF you load that object from the start.
(even if you have manifold selected in the rendering options of developer mode)
(becuase init still uses CSG regardless)
The work around is to load a blank output file, then generate the data using this script.
then, provided you have manifold selected, reloading the data will be much faster.

2. This is true, to 200K objects. at over 200K objects, openscad will default to CSG modeling, which is the same
as being broken.

3. background subtraction concept forgoing complex image processing:
 for h < some min_hight
 render no objects.
 this may help keep object count low, where you can continue to reap the benifits of manifold rendering.
 
 h < 3

'''
