#!/usr/bin/env python3
"""
img2scad.py  Generate a color OpenSCAD heightmap from an image.
Each pixel becomes a colored cube, height based on brightness.

Usage:
  ./img2scad.py input.png

Result:
  input.scad  
  input.3mf   

Requires:
  Pillow, numpy, OpenSCAD in PATH
"""

import sys
import subprocess
from pathlib import Path
from time import sleep
import numpy as np
from PIL import Image

# === CONFIG
MIN_HEIGHT  = 2     # subtracts background noise
PIXEL_SIZE  = 1.0   # mm per pixel (XY)
MAX_HEIGHT  = 10.0  # max Z height (mm)
DOWNSCALE   = 4     # skip every Nth pixel for performance 1=slow >1= faster / lower res


def main() -> int:
    if len(sys.argv) != 2:
        print(f"usage: {Path(sys.argv[0]).name} input_image", file=sys.stderr)
        return 2

    input_image = Path(sys.argv[1])
    if not input_image.exists():
        print(f"error: input not found: {input_image}", file=sys.stderr)
        return 2

    output_scad = input_image.with_suffix(".scad")
    output_3mf  = input_image.with_suffix(".3mf")

    # === LOAD IMAGE ===
    img = Image.open(input_image).convert("RGB")
    data = np.asarray(img, dtype=float)[::DOWNSCALE, ::DOWNSCALE, :]

    # Convert to grayscale for height
    gray = np.dot(data[..., :3], [0.299, 0.587, 0.114])
    heights = gray * (MAX_HEIGHT / 255.0)

    rows, cols, _ = data.shape

    # === WRITE SCAD ===
    with open(output_scad, "w", encoding="utf-8") as f:
        f.write("// Generated by img2scad.py\n")
        for y in range(rows):
            for x in range(cols):
                h = float(heights[y, x])
                if h < MIN_HEIGHT:
                    continue

                r, g, b = (data[y, x] / 255.0)
                f.write(f"color([{r:.3f}, {g:.3f}, {b:.3f}])\n")
                f.write(f"translate([{x * PIXEL_SIZE:.3f}, {y * PIXEL_SIZE:.3f}, 0])\n")
                f.write(f"cube([{PIXEL_SIZE:.3f}, {PIXEL_SIZE:.3f}, {h:.3f}]);\n")

    # === EXPORT 3MF via OpenSCAD CLI ===
    
    print("Gerneatiting 3mf now")
    sleep(2)   # just a wait for scad file gen completion 
    cmd = ["openscad", "-o", str(output_3mf), str(output_scad)]
    try:
        subprocess.run(cmd, check=True)
    except FileNotFoundError:
        print("error: 'openscad' not found in PATH", file=sys.stderr)
        return 127
    except subprocess.CalledProcessError as e:
        return e.returncode

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

'''
Despite having a newer version of openscad
OpenSCAD version 2026.01.06

where outputing a 3mf is an option, color output 
is not supported. or maybe Im doing something wrong.  

'''
